django_waitlist/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.views import (
    logout, password_change, password_change_done, password_reset,
    password_reset_done, password_reset_confirm, password_reset_complete,
)
from django.views.generic import TemplateView, RedirectView

from django.contrib import admin

from django_waitlist.views import sign_up, sign_in, big_transfer

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^ping/", TemplateView.as_view(template_name="ping.json"), name="ping"),
    url(r"^admin/", include(admin.site.urls)),
    url(r'^send_me_elsewhere/$', RedirectView.as_view(url='http://google.com/'), name='send_me_elsewhere'),
    url(r'^waitlist_entries/', include('waitlist_entries.urls', namespace="waitlist_entries")),
    url(r'^vulnerabilities/', include('vulnerabilities.urls', namespace="vulnerabilities")),

    # url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^users/sign_in/$', sign_in, name='login'),
    url(r'^users/sign_out/$', logout, name='logout'),
    url(r'^users/sign_up/$', sign_up, name='register'),
    url(r'^users/password_change/$', password_change, name='password_change'),
    url(r'^users/password_change/done/$', password_change_done, name='password_change_done'),
    url(r'^users/password_reset/$', password_reset, name='password_reset'),
    url(r'^users/password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^users/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^users/reset/done/$', password_reset_complete, name='password_reset_complete'),
    url(r'^big_transfer/$', big_transfer, name='big_transfer'),
]

urlpatterns += [url(r'^number_' + str(i) + '/$', TemplateView.as_view(template_name="homepage.html"), name="home") for i in range(1, 4000)]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waitlist_entries/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^send_me_elsewhere/$', views.send_me_elsewhere, name='send_me_elsewhere'),
]

django_waitlist/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

django_waitlist/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import resolve_url
from django.utils.http import is_safe_url

from django_waitlist.forms import UserForm

def sign_up(request):
    is_registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            is_registered = True

        else:
            print user_form.errors

    else:
        user_form = UserForm()

    context = {'is_registered': is_registered, 'user_form': user_form}

    return render(request, 'registration/register.html', context)

@sensitive_post_parameters()
@csrf_exempt
@never_cache
def sign_in(request,
            _='registration/login.html',
            redirect_field_name=REDIRECT_FIELD_NAME,
            authentication_form=AuthenticationForm,
            __=None):

    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        context = {}
        return render(request, 'registration/login.html', context)


import cStringIO as StringIO
import csv
from django.http import StreamingHttpResponse
def big_transfer(request):
    def stream():
        buffer_ = StringIO.StringIO()
        writer = csv.writer(buffer_)

        for i in range(5000):
            row = ",".join(map(str, range(100)))
            writer.writerow(row)
            buffer_.seek(0)
            data = buffer_.read()
            buffer_.seek(0)
            buffer_.truncate()
            yield data

    response = StreamingHttpResponse(
        stream(), content_type='text/csv'
    )
    disposition = "attachment; filename=file.csv"
    response['Content-Disposition'] = disposition
    return response

django_waitlist/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a id="logout" href="{% url 'logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        {% url "login" as login_url %}
        <li>
            {% blocktrans %}<a href="{{ login_url }}">Log in</a>{% endblocktrans %}
        </li>
        {% url "register" as register_url %}
        <li>
            {% blocktrans %}<a href="{{ register_url }}">Sign up</a>{% endblocktrans %}
        </li>
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'logout' %}" method="POST">
    {% csrf_token %}
</form>

django_waitlist/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2016 &lt;TCell.io&gt;" %}

django_waitlist/templates/_scripts.html
<script src='/static/js/site.js'></script>

django_waitlist/templates/_styles.html
<link href='/static/css/site.css' rel='stylesheet' />

django_waitlist/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load account_tags %}

{% block head_title %}Django Waitlist{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <div class="jumbotron text-center">
      <div class="container">
        <h1>Welcome to TCell's Waitlist</h1>
        {% if not request.user.is_authenticated %}
          {% url "login" as login_url %}
          {% url "register" as register_url %}
          {% blocktrans %}<a href="{{ login_url }}" class="btn btn-lg btn-primary">Log In</a>{% endblocktrans %}
          {% blocktrans %}<a href="{{ register_url }}" class="btn btn-lg btn-primary">Sign Up</a>{% endblocktrans %}
        {% else %}
            <p>Hi, {% user_display request.user %}</p>
        {% endif %}
      </div>
    </div>

    <section>
        <div class="container">
          <h1>django_waitlist</h1>

          <h3>Docker Images</h3>
          <ul>
            <li>web</li>
            <li>tcell_web</li>
            <li>tcell_local_web</li>
          </ul>

          <h3>Setup</h3>

          <ul>
            <li>1. docker-compose build</li>
            <li>2. sh docker/initial_setup.sh # needs `psql`. creates db and seeds it.</li>
            <li>3. docker-compose up web (tcell_web|tcell_local_web)</li>
          </ul>

          <h3>Vulnerabilities</h3>

          <ul>
            <li>`http://host:port/vulnerabilities/search`</li>
            <li>Input from search form is executed raw in the db thereby creating a security hole</li>
            <li>&nbsp;</li>
            <li>`http://host:port/vulnerabilities/sql_exception/`</li>
            <li>Raw sql is malformed so it will raise an sql exception</li>
          </ul>
        </div>
    </section>
{% endblock %}

django_waitlist/templates/site_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8" />
        <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} | {% endif %}{% block head_title %}{% endblock %}{% endblock %}</title>
        {% block viewport %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% endblock %}

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        {% include "_styles.html" %}

        {% block html5shim %}
            <!-- HTML5 shim, for IE6-8 support of HTML elements -->
            <!--[if lt IE 9]>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
            <![endif]-->
        {% endblock %}

        {% block extra_head_base %}
            {% block extra_head %}{% endblock %}
        {% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}" {% block body_extra_attributes %}{% endblock %}>
        <div class="{% block wrapper_class %}{% endblock %}">

            {% block topbar_base %}
            <nav class="navbar navbar-default navbar-static-top navbar-inverse">
              <div class="container">
                <ul class="nav navbar-nav">
                  <li>
                    <a href="{% url "home" %}"><span class="glyphicon glyphicon-home"></span> Home</a>
                  </li>
                  <li>
                    <a href="{% url "waitlist_entries:index" %}">Waitlist</a>
                  </li>
                </ul>

                {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
              </div>
            </nav>
            {% endblock %}

            {% block body_base %}
                <section id="content_body">
                    <div class="container">
                        {% block body %}
                        {% endblock %}
                    </div>
                </section>
            {% endblock %}

            {% block footer_base %}
                <hr />
                <footer>
                    <div class="container">
                        {% include "_footer.html" %}
                    </div>
                </footer>
            {% endblock %}
        </div>

        {% include "_scripts.html" %}

        {% block extra_body_base %}
            {% block extra_body %}{% endblock %}
        {% endblock %}
    </body>
</html>